### ISSUE TITLE
CORS config does not update as expected after changes to Environments and Portals

### ISSUE THREAD

**Issue by kcbabo** [solo-io/gloo-portal-issues#154]
**Describe the bug**
Unable to invoke an API from developer portal when that API does not have an associated usage plan. This appears to be due to the fact that CORS config not generated without a usage plan. If I add a usage plan to the API, then the CORS config is generated and the API can be invoked in the portal.

**To Reproduce**
1. Create a portal for an API with no usage plan.
2. Invoke the API from the portal.

**Expected behavior**
Generate CORS configuration whether there is a usage plan or not.

**Comment by marcogschmidt** [comment]
After investigating the issue, we determined that the problem is not related to usage plans, but is actually caused by a bug in the event handling logic of the portal controller. The bug causes the CORS configuration to go stale when some specific changes are applied to `Environments` and `Portals` they are published in. The issue has been fixed and will be released with version `v1.2.0-beta8`.
